# Site settings
title: ModernPGP
email: yay@moderpgp.org
description: > # this means to ignore newlines until "baseurl:"
  A working group that is bringing the party to the crypto by 
  improving the state of all things PGP for developers to 
  end users.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://modernpgp.org" # the base hostname & protocol for your site
github_username:  modernpgp

exclude: ["CNAME"]

# Build settings
markdown: kramdown
